id: AB8B24BEB
base_file: f7B18.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:56:03.915213
  last_modified_at: 2022-06-17 12:56:03.915216
