id: AB8B24BEB
base_file: f1FDB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:56:03.910252
  last_modified_at: 2022-06-17 12:56:03.910258
