id: AB8B24BEB
base_file: fADA1.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:56:03.917442
  last_modified_at: 2022-06-17 12:56:03.917445
