id: AB8B24BEB
base_file: f9279.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:56:03.916381
  last_modified_at: 2022-06-17 12:56:03.916383
